#### About Pandas

1. It is an open source DATA ANALYSIS library written in python.
2. it leverages the power and speed of numpy to make data analysis and preprocessing easy for data scientists.
3. it provides riech and highly robust data operations.
4. numpy is written in c/c++.

In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name" : ["vaibhav", "harsh", "praful", "Jay"],
    "marks" : [10, 8, 9, 7],
    "city" : ["jhansi", "gonda", "agra", "Jaipur"]
}

DataFrame is just like Excel sheet

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

      name  marks    city
0  vaibhav     10  jhansi
1    harsh      8   gonda
2   praful      9    agra
3      Jay      7  Jaipur

Exporting dataframe into csv file

In [5]:
df.to_csv('friendsInfo.csv')

If we don't want index in my csv file then use index=false in to_csv() funcction

In [6]:
df.to_csv('friendsInfoWithNoIndex.csv', index=False)

if let say we have a very big data set , consisting of 1 million row,
then our dataframe will show only few top rows.
1. we can use head(count) function to see above top rows.
2. we can use tail(count) function to see below rows.

In [7]:
df.head(2)

      name  marks    city
0  vaibhav     10  jhansi
1    harsh      8   gonda

In [8]:
df.tail(2)

     name  marks    city
2  praful      9    agra
3     Jay      7  Jaipur

describe() function perform all the mathematical operations of the numeric column, which is thier in Dataframe

In [9]:
df.describe()

           marks
count   4.000000
mean    8.500000
std     1.290994
min     7.000000
25%     7.750000
50%     8.500000
75%     9.250000
max    10.000000

In [10]:
train_data_frame = pd.read_csv('Train.csv')

In [11]:
train_data_frame

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,TRAIN NO,speed,city
0,0,0,0,0,0,0,0,12345,100,jhansi
1,1,1,1,1,1,1,1,23456,60,gonda
2,2,2,2,2,2,2,2,34567,40,agra
3,3,3,3,3,3,3,3,45678,70,Jaipur

In [12]:
train_data_frame['speed']

0    100
1     60
2     40
3     70
Name: speed, dtype: int64

In [13]:
train_data_frame['speed'][0]

np.int64(100)

Changing the value of speed which is at index 0,
but changing like this is discarded but still changing it like this for learning purpose

In [14]:
train_data_frame['speed'][0] = 100

C:\Users\ASUS\AppData\Local\Temp\ipykernel_18792\4230915258.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data_frame['speed'][0] = 100

In [15]:
train_data_frame

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,TRAIN NO,speed,city
0,0,0,0,0,0,0,0,12345,100,jhansi
1,1,1,1,1,1,1,1,23456,60,gonda
2,2,2,2,2,2,2,2,34567,40,agra
3,3,3,3,3,3,3,3,45678,70,Jaipur

In [16]:
train_data_frame.to_csv('Train.csv')

In [17]:
train_data_frame

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,TRAIN NO,speed,city
0,0,0,0,0,0,0,0,12345,100,jhansi
1,1,1,1,1,1,1,1,23456,60,gonda
2,2,2,2,2,2,2,2,34567,40,agra
3,3,3,3,3,3,3,3,45678,70,Jaipur

changing the index variety

In [18]:
train_data_frame.index = ['First','Second','Third','Fourth']

In [19]:
train_data_frame

,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,TRAIN NO,speed,city
First,0,0,0,0,0,0,0,12345,100,jhansi
Second,1,1,1,1,1,1,1,23456,60,gonda
Third,2,2,2,2,2,2,2,34567,40,agra
Fourth,3,3,3,3,3,3,3,45678,70,Jaipur

#### Python data structure

pandas have two tyoes of data structure:-
a) series
b) Dataframe
1. a one dimesnional array(labellled) capable of hodling any type of data - series.
2. a two dimensional data(labelled) structure with colimn of potentially diffrerent data types of data - DataFrame.

In [20]:
ser = pd.Series(np.random.rand(30))

In [21]:
ser

0     0.670870
1     0.222278
2     0.603933
3     0.993558
4     0.395693
5     0.065630
6     0.203058
7     0.714945
8     0.036704
9     0.973890
10    0.753594
11    0.764337
12    0.401473
13    0.031567
14    0.897180
15    0.920787
16    0.182409
17    0.077763
18    0.201473
19    0.780404
20    0.174460
21    0.800734
22    0.957212
23    0.978449
24    0.978667
25    0.711377
26    0.964849
27    0.989093
28    0.697486
29    0.500047
dtype: float64

In [22]:
type(ser)

pandas.core.series.Series

In [23]:
newdf = pd.DataFrame(np.random.rand(334, 5), index=np.arange(334))

In [24]:
newdf

            0         1         2         3         4
0    0.916229  0.984212  0.834988  0.993767  0.089914
1    0.658077  0.160391  0.104796  0.274009  0.907108
2    0.526740  0.953060  0.124875  0.649086  0.586841
3    0.419691  0.757096  0.412863  0.687056  0.398360
4    0.198281  0.372091  0.095296  0.838360  0.212714
..        ...       ...       ...       ...       ...
329  0.773968  0.395987  0.775524  0.965443  0.197256
330  0.069766  0.820366  0.668201  0.027920  0.768646
331  0.027937  0.771857  0.577411  0.666277  0.818189
332  0.689321  0.079267  0.956868  0.666709  0.211174
333  0.705462  0.273935  0.886699  0.494252  0.808560

[334 rows x 5 columns]

In [25]:
type(newdf)

pandas.core.frame.DataFrame

performing all statical operations by the describe() method

In [26]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.521790    0.496676    0.526821    0.497521    0.509734
std      0.297307    0.285486    0.289709    0.297196    0.290389
min      0.011309    0.000791    0.012175    0.000316    0.004718
25%      0.261593    0.256280    0.281511    0.233175    0.269427
50%      0.530147    0.482879    0.535159    0.486938    0.488714
75%      0.801465    0.748077    0.804049    0.761356    0.768591
max      0.999220    0.998671    0.998677    0.998442    0.999459

In [27]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

checking datatypes with the help of dtypes

In [28]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [29]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

Converting the pandas dataframe to numpy array.

In [30]:
newdf.to_numpy()

array([[0.91622864, 0.98421221, 0.83498786, 0.99376742, 0.08991381],
       [0.6580766 , 0.16039141, 0.10479574, 0.27400943, 0.90710818],
       [0.52674038, 0.95306026, 0.12487474, 0.64908645, 0.58684131],
       ...,
       [0.02793671, 0.77185682, 0.57741148, 0.66627735, 0.81818858],
       [0.68932062, 0.07926728, 0.9568676 , 0.66670903, 0.21117429],
       [0.70546183, 0.27393482, 0.88669851, 0.49425154, 0.8085595 ]],
      shape=(334, 5))

In [31]:
newdf.head()

          0         1         2         3         4
0  0.916229  0.984212  0.834988  0.993767  0.089914
1  0.658077  0.160391  0.104796  0.274009  0.907108
2  0.526740  0.953060  0.124875  0.649086  0.586841
3  0.419691  0.757096  0.412863  0.687056  0.398360
4  0.198281  0.372091  0.095296  0.838360  0.212714

taking transpose

In [32]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.916229,0.658077,0.526740,0.419691,0.198281,0.582746,0.629731,0.791347,0.178379,0.596750,...,0.840340,0.965052,0.444767,0.635458,0.227499,0.773968,0.069766,0.027937,0.689321,0.705462
1,0.984212,0.160391,0.953060,0.757096,0.372091,0.117621,0.105089,0.000791,0.240960,0.789932,...,0.673985,0.629733,0.314074,0.576566,0.050373,0.395987,0.820366,0.771857,0.079267,0.273935
2,0.834988,0.104796,0.124875,0.412863,0.095296,0.281134,0.714235,0.524222,0.780984,0.299798,...,0.524863,0.800651,0.889003,0.173009,0.183675,0.775524,0.668201,0.577411,0.956868,0.886699
3,0.993767,0.274009,0.649086,0.687056,0.838360,0.851555,0.734473,0.490037,0.366059,0.110578,...,0.950387,0.794227,0.258595,0.867112,0.968024,0.965443,0.027920,0.666277,0.666709,0.494252
4,0.089914,0.907108,0.586841,0.398360,0.212714,0.474518,0.206494,0.983565,0.775470,0.907133,...,0.336978,0.647600,0.682857,0.015993,0.460503,0.197256,0.768646,0.818189,0.211174,0.808560

In [33]:
newdf.head()

          0         1         2         3         4
0  0.916229  0.984212  0.834988  0.993767  0.089914
1  0.658077  0.160391  0.104796  0.274009  0.907108
2  0.526740  0.953060  0.124875  0.649086  0.586841
3  0.419691  0.757096  0.412863  0.687056  0.398360
4  0.198281  0.372091  0.095296  0.838360  0.212714

now sorting the index. according to requirement

sort_index() method is used for sorting dataframes index.

In [34]:
newdf.sort_index(axis=0, ascending=False)

            0         1         2         3         4
333  0.705462  0.273935  0.886699  0.494252  0.808560
332  0.689321  0.079267  0.956868  0.666709  0.211174
331  0.027937  0.771857  0.577411  0.666277  0.818189
330  0.069766  0.820366  0.668201  0.027920  0.768646
329  0.773968  0.395987  0.775524  0.965443  0.197256
..        ...       ...       ...       ...       ...
4    0.198281  0.372091  0.095296  0.838360  0.212714
3    0.419691  0.757096  0.412863  0.687056  0.398360
2    0.526740  0.953060  0.124875  0.649086  0.586841
1    0.658077  0.160391  0.104796  0.274009  0.907108
0    0.916229  0.984212  0.834988  0.993767  0.089914

[334 rows x 5 columns]

rows is our axis=0 and column is our axis=1.

In [35]:
newdf.sort_index(axis=1, ascending=False)

            4         3         2         1         0
0    0.089914  0.993767  0.834988  0.984212  0.916229
1    0.907108  0.274009  0.104796  0.160391  0.658077
2    0.586841  0.649086  0.124875  0.953060  0.526740
3    0.398360  0.687056  0.412863  0.757096  0.419691
4    0.212714  0.838360  0.095296  0.372091  0.198281
..        ...       ...       ...       ...       ...
329  0.197256  0.965443  0.775524  0.395987  0.773968
330  0.768646  0.027920  0.668201  0.820366  0.069766
331  0.818189  0.666277  0.577411  0.771857  0.027937
332  0.211174  0.666709  0.956868  0.079267  0.689321
333  0.808560  0.494252  0.886699  0.273935  0.705462

[334 rows x 5 columns]

In [36]:
newdf.head()

          0         1         2         3         4
0  0.916229  0.984212  0.834988  0.993767  0.089914
1  0.658077  0.160391  0.104796  0.274009  0.907108
2  0.526740  0.953060  0.124875  0.649086  0.586841
3  0.419691  0.757096  0.412863  0.687056  0.398360
4  0.198281  0.372091  0.095296  0.838360  0.212714

newdf[0] will give us whole column named 0. --> it will be a series.

In [37]:
newdf[0]

0      0.916229
1      0.658077
2      0.526740
3      0.419691
4      0.198281
         ...
329    0.773968
330    0.069766
331    0.027937
332    0.689321
333    0.705462
Name: 0, Length: 334, dtype: float64

In [38]:
type(newdf[0])

pandas.core.series.Series

About VIEW --> important concept.

In [39]:
newdf2 = newdf

newdf2 is a view of newdf, not the copy of newdf

In [40]:
newdf2[0][0] = 9898

In [41]:
newdf

               0         1         2         3         4
0    9898.000000  0.984212  0.834988  0.993767  0.089914
1       0.658077  0.160391  0.104796  0.274009  0.907108
2       0.526740  0.953060  0.124875  0.649086  0.586841
3       0.419691  0.757096  0.412863  0.687056  0.398360
4       0.198281  0.372091  0.095296  0.838360  0.212714
..           ...       ...       ...       ...       ...
329     0.773968  0.395987  0.775524  0.965443  0.197256
330     0.069766  0.820366  0.668201  0.027920  0.768646
331     0.027937  0.771857  0.577411  0.666277  0.818189
332     0.689321  0.079267  0.956868  0.666709  0.211174
333     0.705462  0.273935  0.886699  0.494252  0.808560

[334 rows x 5 columns]

clearly seen that changes made in newdf2 get reflected in newdf.

1. newdf2 = newdf --> newdf pura ka pura copy hokai nya nhi banega in newdf2.
2. newdf2 is a view of newdf.
3. newdf2 ko as a pointer ki tarah samjh lo, jo ki newdf ki tarah point kar rha hai.
4. newdf2 change hoga toh newdf bhi change ho jaigaa.

now to copy the newdf to newdf2 such that both becomes independent to each other, changing one's value will not effect the
other value --> to do this we use copy() function.

In [42]:
newdf2 = newdf.copy()

In [43]:
newdf2[0][0] = 10000

C:\Users\ASUS\AppData\Local\Temp\ipykernel_18792\491525003.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0] = 10000

this above warning is regarding to that view and copy concept --> warning is saying newdf2 is not a view of newdf, so on changing newdf2 it will not effect the newdf, instead changes made are now independent to each other.

In [44]:
newdf.head()

             0         1         2         3         4
0  9898.000000  0.984212  0.834988  0.993767  0.089914
1     0.658077  0.160391  0.104796  0.274009  0.907108
2     0.526740  0.953060  0.124875  0.649086  0.586841
3     0.419691  0.757096  0.412863  0.687056  0.398360
4     0.198281  0.372091  0.095296  0.838360  0.212714

kabhi kabhi yeh track karna muskil ho jata hai kya return hoga - view or copy - pandas kabhi kabhi apni internal memory management kai hisaab sai decide karta hai ki kya return karna chaiye.

that why whenever we have to change the value or set the value to row, column- we will use loc[] [lock].

changing the columns

In [45]:
newdf.head(2)

             0         1         2         3         4
0  9898.000000  0.984212  0.834988  0.993767  0.089914
1     0.658077  0.160391  0.104796  0.274009  0.907108

In [46]:
newdf.columns = list('ABCDE')

In [47]:
newdf.head(2)

             A         B         C         D         E
0  9898.000000  0.984212  0.834988  0.993767  0.089914
1     0.658077  0.160391  0.104796  0.274009  0.907108

changing value by loc()

In [48]:
newdf.loc[0,'A'] = 123321

In [49]:
newdf.head(2)

               A         B         C         D         E
0  123321.000000  0.984212  0.834988  0.993767  0.089914
1       0.658077  0.160391  0.104796  0.274009  0.907108

In [50]:
newdf.loc[0,0] = 19191

In [51]:
newdf.head()

               A         B         C         D         E        0
0  123321.000000  0.984212  0.834988  0.993767  0.089914  19191.0
1       0.658077  0.160391  0.104796  0.274009  0.907108      NaN
2       0.526740  0.953060  0.124875  0.649086  0.586841      NaN
3       0.419691  0.757096  0.412863  0.687056  0.398360      NaN
4       0.198281  0.372091  0.095296  0.838360  0.212714      NaN

Now to drop the column name 0 we will use drop() funtion.

In [52]:
newdf = newdf.drop(0, axis=1)

In [53]:
newdf.head()

               A         B         C         D         E
0  123321.000000  0.984212  0.834988  0.993767  0.089914
1       0.658077  0.160391  0.104796  0.274009  0.907108
2       0.526740  0.953060  0.124875  0.649086  0.586841
3       0.419691  0.757096  0.412863  0.687056  0.398360
4       0.198281  0.372091  0.095296  0.838360  0.212714

if we want the particular rows and columns and getting it by loc() -- how?

loc[[1,2], ['C','D']] means get me rows name 1 and 2 , also get me columns name C and D.

In [54]:
newdf.loc[[1,2], ['C','D']]

          C         D
1  0.104796  0.274009
2  0.124875  0.649086

retuns a new data frame.

to get all the rows or columns we use  :  in loc[]

In [55]:
newdf.loc[:, ['C','D']]

            C         D
0    0.834988  0.993767
1    0.104796  0.274009
2    0.124875  0.649086
3    0.412863  0.687056
4    0.095296  0.838360
..        ...       ...
329  0.775524  0.965443
330  0.668201  0.027920
331  0.577411  0.666277
332  0.956868  0.666709
333  0.886699  0.494252

[334 rows x 2 columns]

In [56]:
newdf.loc[[1,2], :]

          A         B         C         D         E
1  0.658077  0.160391  0.104796  0.274009  0.907108
2  0.526740  0.953060  0.124875  0.649086  0.586841

running the complex queries using loc[]

i want only those value to be appear in column A whose cells containing value must be smaller than 0.3

In [57]:
newdf.loc[(newdf['A'] < 0.3)]

            A         B         C         D         E
4    0.198281  0.372091  0.095296  0.838360  0.212714
8    0.178379  0.240960  0.780984  0.366059  0.775470
12   0.291296  0.708872  0.552796  0.027630  0.311491
19   0.118598  0.822632  0.200398  0.501677  0.950574
22   0.089785  0.790030  0.083843  0.131528  0.359899
..        ...       ...       ...       ...       ...
322  0.056793  0.833657  0.379887  0.959716  0.961917
323  0.144998  0.176757  0.072189  0.004881  0.088664
328  0.227499  0.050373  0.183675  0.968024  0.460503
330  0.069766  0.820366  0.668201  0.027920  0.768646
331  0.027937  0.771857  0.577411  0.666277  0.818189

[98 rows x 5 columns]

we get only those cells of column A which is containing the values smaller than 0.3

In [58]:
newdf.loc[(newdf['A'] < 0.3) & (newdf['C'] > 0.1)]

            A         B         C         D         E
8    0.178379  0.240960  0.780984  0.366059  0.775470
12   0.291296  0.708872  0.552796  0.027630  0.311491
19   0.118598  0.822632  0.200398  0.501677  0.950574
23   0.094199  0.275493  0.237568  0.553418  0.423653
25   0.234497  0.943363  0.359406  0.900294  0.775703
..        ...       ...       ...       ...       ...
321  0.240280  0.719010  0.742656  0.382171  0.644625
322  0.056793  0.833657  0.379887  0.959716  0.961917
328  0.227499  0.050373  0.183675  0.968024  0.460503
330  0.069766  0.820366  0.668201  0.027920  0.768646
331  0.027937  0.771857  0.577411  0.666277  0.818189

[89 rows x 5 columns]

IMPORTANT --> loc[] mai hum df kai rows and columns unkai index kai naam ya phir columns kai naam sai select kar saktai hai.

So if we have to get the rows and columns by the help of pure index, getting element by the help of index, no worrying of what the name of row is or column is.--> we will use  -->>  iloc[]

to get the rows and column of the df by the help of the labels (name of rows and columns) --> we will use the  loc[].

In [59]:
newdf.head(3)

               A         B         C         D         E
0  123321.000000  0.984212  0.834988  0.993767  0.089914
1       0.658077  0.160391  0.104796  0.274009  0.907108
2       0.526740  0.953060  0.124875  0.649086  0.586841

In [60]:
newdf.iloc[0,4]

np.float64(0.08991380845846242)

gives the value present at row 0 and column E.

In [61]:
newdf.iloc[[0,1],[1,2]]

          B         C
0  0.984212  0.834988
1  0.160391  0.104796

iloc[[0,1],[1,2]] means i want row 0 and 1, column 1 and 2.

In [62]:
newdf.head(5)

               A         B         C         D         E
0  123321.000000  0.984212  0.834988  0.993767  0.089914
1       0.658077  0.160391  0.104796  0.274009  0.907108
2       0.526740  0.953060  0.124875  0.649086  0.586841
3       0.419691  0.757096  0.412863  0.687056  0.398360
4       0.198281  0.372091  0.095296  0.838360  0.212714

In [63]:
newdf.iloc[[2,3,4,5],[2,3]]

          C         D
2  0.124875  0.649086
3  0.412863  0.687056
4  0.095296  0.838360
5  0.281134  0.851555

index [2,3,4,5] represent rows and index[2,3] represent column C and D.

In [64]:
newdf.head(3)

               A         B         C         D         E
0  123321.000000  0.984212  0.834988  0.993767  0.089914
1       0.658077  0.160391  0.104796  0.274009  0.907108
2       0.526740  0.953060  0.124875  0.649086  0.586841

In [65]:
newdf.drop(0, axis=0)

            A         B         C         D         E
1    0.658077  0.160391  0.104796  0.274009  0.907108
2    0.526740  0.953060  0.124875  0.649086  0.586841
3    0.419691  0.757096  0.412863  0.687056  0.398360
4    0.198281  0.372091  0.095296  0.838360  0.212714
5    0.582746  0.117621  0.281134  0.851555  0.474518
..        ...       ...       ...       ...       ...
329  0.773968  0.395987  0.775524  0.965443  0.197256
330  0.069766  0.820366  0.668201  0.027920  0.768646
331  0.027937  0.771857  0.577411  0.666277  0.818189
332  0.689321  0.079267  0.956868  0.666709  0.211174
333  0.705462  0.273935  0.886699  0.494252  0.808560

[333 rows x 5 columns]

In [66]:
newdf.drop(['A', 'C'], axis=1)

            B         D         E
0    0.984212  0.993767  0.089914
1    0.160391  0.274009  0.907108
2    0.953060  0.649086  0.586841
3    0.757096  0.687056  0.398360
4    0.372091  0.838360  0.212714
..        ...       ...       ...
329  0.395987  0.965443  0.197256
330  0.820366  0.027920  0.768646
331  0.771857  0.666277  0.818189
332  0.079267  0.666709  0.211174
333  0.273935  0.494252  0.808560

[334 rows x 3 columns]

In [67]:
newdf

                 A         B         C         D         E
0    123321.000000  0.984212  0.834988  0.993767  0.089914
1         0.658077  0.160391  0.104796  0.274009  0.907108
2         0.526740  0.953060  0.124875  0.649086  0.586841
3         0.419691  0.757096  0.412863  0.687056  0.398360
4         0.198281  0.372091  0.095296  0.838360  0.212714
..             ...       ...       ...       ...       ...
329       0.773968  0.395987  0.775524  0.965443  0.197256
330       0.069766  0.820366  0.668201  0.027920  0.768646
331       0.027937  0.771857  0.577411  0.666277  0.818189
332       0.689321  0.079267  0.956868  0.666709  0.211174
333       0.705462  0.273935  0.886699  0.494252  0.808560

[334 rows x 5 columns]

1. if want to change the newdf then we have to write somewhalike this newdf = newdf.drop(['A', 'C'], axis=1).
2. otherwise writing only newdf.drop(['A', 'C'], axis-=1). this will return a copy of the df and our original newdf remains the same (unchanged).

1. to modify the original df or change the original df, wothout writing this --> newdf = newdf.drop(['A', 'C'], axis=1).
2. we will have to use inplace = True inside that function.
3. newdf = newdf.drop(['A', 'C'], axis=1, inplace = True) --> will chnage the original df.

In [68]:
newdf.drop(['A', 'C'], axis=1, inplace=True)

In [69]:
newdf

            B         D         E
0    0.984212  0.993767  0.089914
1    0.160391  0.274009  0.907108
2    0.953060  0.649086  0.586841
3    0.757096  0.687056  0.398360
4    0.372091  0.838360  0.212714
..        ...       ...       ...
329  0.395987  0.965443  0.197256
330  0.820366  0.027920  0.768646
331  0.771857  0.666277  0.818189
332  0.079267  0.666709  0.211174
333  0.273935  0.494252  0.808560

[334 rows x 3 columns]

In [70]:
newdf.drop([1,2,3,5,331,332], axis=0, inplace=True)

In [71]:
newdf

            B         D         E
0    0.984212  0.993767  0.089914
4    0.372091  0.838360  0.212714
6    0.105089  0.734473  0.206494
7    0.000791  0.490037  0.983565
8    0.240960  0.366059  0.775470
..        ...       ...       ...
327  0.576566  0.867112  0.015993
328  0.050373  0.968024  0.460503
329  0.395987  0.965443  0.197256
330  0.820366  0.027920  0.768646
333  0.273935  0.494252  0.808560

[328 rows x 3 columns]

reseting the index again to 0,1,2,3,4.... --> we have to use the reset_index().

In [72]:
newdf.reset_index()

     index         B         D         E
0        0  0.984212  0.993767  0.089914
1        4  0.372091  0.838360  0.212714
2        6  0.105089  0.734473  0.206494
3        7  0.000791  0.490037  0.983565
4        8  0.240960  0.366059  0.775470
..     ...       ...       ...       ...
323    327  0.576566  0.867112  0.015993
324    328  0.050373  0.968024  0.460503
325    329  0.395987  0.965443  0.197256
326    330  0.820366  0.027920  0.768646
327    333  0.273935  0.494252  0.808560

[328 rows x 4 columns]

this function automatically add the name of the index column - i dont want this just pass argument drop=True.

In [73]:
newdf.reset_index(drop=True, inplace=True)

In [74]:
newdf.head()

          B         D         E
0  0.984212  0.993767  0.089914
1  0.372091  0.838360  0.212714
2  0.105089  0.734473  0.206494
3  0.000791  0.490037  0.983565
4  0.240960  0.366059  0.775470

how to remove null from pandas dataframes.

how to remove duplicate in pandas.

In [75]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
323    False
324    False
325    False
326    False
327    False
Name: B, Length: 328, dtype: bool

isnull() retuns true if any cell is null (conatins zero value).

i want to set all the values on column B to None.

In [76]:
newdf.loc[:, ['B']] = None

C:\Users\ASUS\AppData\Local\Temp\ipykernel_18792\3746458820.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'None' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf.loc[:, ['B']] = None

In [77]:
newdf

        B         D         E
0    None  0.993767  0.089914
1    None  0.838360  0.212714
2    None  0.734473  0.206494
3    None  0.490037  0.983565
4    None  0.366059  0.775470
..    ...       ...       ...
323  None  0.867112  0.015993
324  None  0.968024  0.460503
325  None  0.965443  0.197256
326  None  0.027920  0.768646
327  None  0.494252  0.808560

[328 rows x 3 columns]

In [78]:
newdf['B'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
323    True
324    True
325    True
326    True
327    True
Name: B, Length: 328, dtype: bool

other functions:-

In [79]:
dict = {
    "name": ["vaibhav", "jay", "praful"],
    "toy": [np.nan, "batmobile", "bolwhip"],
    "born": [pd.NaT, pd.Timestamp("2007-12-04"), pd.NaT]
}

In [80]:
df = pd.DataFrame(dict)

In [81]:
df

      name        toy       born
0  vaibhav        NaN        NaT
1      jay  batmobile 2007-12-04
2   praful    bolwhip        NaT

In [82]:
df.dropna()

  name        toy       born
1  jay  batmobile 2007-12-04

jha jha na tha uss row ko hta diya --> dropna()

to drop the column,  when all its element becomes Nan - use how attribute inside dropna().

In [83]:
df.dropna(how='all', axis=1)

      name        toy       born
0  vaibhav        NaN        NaT
1      jay  batmobile 2007-12-04
2   praful    bolwhip        NaT

In [84]:
df.loc[[1,2], ['toy']] = np.nan

In [85]:
df

      name  toy       born
0  vaibhav  NaN        NaT
1      jay  NaN 2007-12-04
2   praful  NaN        NaT

In [86]:
df.dropna(how='all', axis=1)

      name       born
0  vaibhav        NaT
1      jay 2007-12-04
2   praful        NaT

In [87]:
df

      name  toy       born
0  vaibhav  NaN        NaT
1      jay  NaN 2007-12-04
2   praful  NaN        NaT

In [88]:
df.loc[2, 'name'] = "vaibhav"

In [89]:
df

      name  toy       born
0  vaibhav  NaN        NaT
1      jay  NaN 2007-12-04
2  vaibhav  NaN        NaT

now removing the duplicates

In [90]:
df.drop_duplicates()

      name  toy       born
0  vaibhav  NaN        NaT
1      jay  NaN 2007-12-04

In [91]:
df.drop_duplicates(subset=['name'])

      name  toy       born
0  vaibhav  NaN        NaT
1      jay  NaN 2007-12-04

keep attribute of drop_duplicate() --> its default value is first

In [92]:
df.drop_duplicates(subset=['name'], keep='first')

      name  toy       born
0  vaibhav  NaN        NaT
1      jay  NaN 2007-12-04

In [93]:
df.drop_duplicates(subset=['name'], keep='last')

      name  toy       born
1      jay  NaN 2007-12-04
2  vaibhav  NaN        NaT

In [94]:
df.drop_duplicates(subset=['name'], keep=False)

  name  toy       born
1  jay  NaN 2007-12-04

keep = False --> will completely removes that record.

other things in pandas:-

In [95]:
df.shape

(3, 3)

shape --> (no of rows, no of columns)

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   toy     0 non-null      object
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 204.0+ bytes

In [97]:
df

      name  toy       born
0  vaibhav  NaN        NaT
1      jay  NaN 2007-12-04
2  vaibhav  NaN        NaT

In [98]:
df.loc[1, 'toy'] = "mouse"

In [99]:
df.loc[2, 'toy'] = "keu=yboard"

In [100]:
df['toy'].value_counts(dropna=False)

toy
NaN           1
mouse         1
keu=yboard    1
Name: count, dtype: int64

In [101]:
df['toy'].value_counts(dropna=True)

toy
mouse         1
keu=yboard    1
Name: count, dtype: int64

1. dropna = False --> counts the nan also.
2. dropna = True --> dont count the nan, remove the nan.

In [102]:
df.notnull()

   name    toy   born
0  True  False  False
1  True   True   True
2  True   True  False

Statistical operations on data.
1. df.describe()
2. df.mean()
3. df.corr()
4. df.count()
5. df.max()
6. df.min()
7. df.median()
8. df.std()

### How to read Excel sheet file by pandas.

In [110]:
data = pd.read_excel('data.xlsx')

Download xlrd module -- beacause pandas required it to work with the excel sheets -- to read the excel sheet.

Download openpyxl module -- beacause pandas required it to work with the excel sheets -- to write in the excel sheet.

In [111]:
data

   TRAIN NO  speed    city
0     12345    190  jhansi
1     23456    160   gonda
2     34567    140    agra
3     45678    170  Jaipur

In [112]:
data2 = pd.read_excel('data.xlsx', sheet_name='Sheet2')

data2

Writing in Excel

In [115]:
data.iloc[0,0] = 121

In [117]:
data.iloc[1,0] = 212

In [118]:
data.iloc[2,1] = 200

In [119]:
data

   TRAIN NO  speed    city
0       121    190  jhansi
1       212    160   gonda
2     34567    200    agra
3     45678    170  Jaipur

In [121]:
data.to_excel('data.xlsx', sheet_name='Sheet3')

But above code will remove sheet1 and Sheet2 and write Sheet3

Find how to write in sheet2 without removing sheet1